apiVersion: v1
kind: Service
metadata:
  name: $IMAGE_NAME-$ENVIRONMENT-svc
  namespace: $NAMESPACE
spec:
  selector:
    app: "$KUBERNETES_NAME"
    version: $VERSION
    environment: "$ENVIRONMENT"
  type: NodePort
  ports:
    - protocol: TCP
      port: $PORT
      targetPort: $PORT
      nodePort: $EXPOSE_PORT

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: $BACKEND_CONFIG_MAP
  namespace: $NAMESPACE
data:
  PORT: "$PORT"
  ENVIRONMENT: "$ENVIRONMENT"
  VERSION: "$VERSION"
  MODULE_NAME: "$MODULE_NAME"
  IMAGE_NAME: "$IMAGE_NAME"
  SPRING_DATASOURCE_URL: "$SPRING_DATASOURCE_URL"
  SPRING_DATASOURCE_USERNAME: "$SPRING_DATASOURCE_USERNAME"
  SPRING_DATASOURCE_PASSWORD: "$SPRING_DATASOURCE_PASSWORD"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "$KUBERNETES_NAME"
  namespace: $NAMESPACE
  labels:
    app: "$KUBERNETES_NAME"
    version: "$VERSION"
    environment: "$ENVIRONMENT"
spec:
  selector:
    matchLabels:
      app: "$KUBERNETES_NAME"
  template:
    metadata:
      labels:
        app: "$KUBERNETES_NAME"
        version: "$VERSION"
        environment: "$ENVIRONMENT"
    spec:
      containers:
        - name: $IMAGE_NAME
          image: adamantinoo/$IMAGE_TAG
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: $BACKEND_CONFIG_MAP
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: $BACKEND_CONFIG_MAP
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: $BACKEND_CONFIG_MAP
                  key: SPRING_DATASOURCE_PASSWORD
          ports:
            - containerPort: $PORT
          imagePullPolicy: Always
      serviceAccountName: default
