./gradlew test -Dcucumber.options="--tags @P3D01"
./gradlew test -Dcucumber.options="--tags @P3D02"
./gradlew test -Dcucumber.options="--tags @P3D03"
./gradlew test -Dcucumber.options="--tags @P3D04"
./gradlew test -Dcucumber.options="--tags @P3D05"
./gradlew test -Dcucumber.options="--tags @P3D06"
./gradlew test -Dcucumber.options="--tags @P3D07"
./gradlew test -Dcucumber.options="--tags @P3D08"
