package org.dimensinfin.printer3d.backend.support;

public enum RequestType {
	NEW_PART,
	UPDATE_PART,
	GET_PARTS,
	NEW_COIL,
	GET_COILS,
	GET_FINISHINGS,
	GET_MACHINES_V1,
	GET_MACHINES_V2,
	START_BUILD,
	START_BUILDV2,
	CANCEL_BUILD,
	COMPLETE_BUILD,
	GET_JOBS,
	NEW_MODEL,
	UPDATE_MODEL,
	GET_MODELS,
	ADD_MODEL_PART,
	REMOVE_MODEL_PART,
	NEW_REQUEST,
	GET_REQUESTS,
	CLOSE_REQUEST;
}
