package org.dimensinfin.printer3d.backend.support;

public enum RequestType {
	NEW_PART,
	UPDATE_PART,
	UPDATE_GROUP_PART,
	GET_PARTS,
	NEW_COIL,
	GET_COILS,
	UPDATE_COIL,
	GET_FINISHINGS,
	GET_MACHINES_V2,
	START_BUILDV2,
	CANCEL_BUILD,
	COMPLETE_BUILD,
	GET_JOBS,
	NEW_MODEL,
	UPDATE_MODEL,
	GET_MODELS,
	ADD_MODEL_PART,
	REMOVE_MODEL_PART,
//	NEW_REQUEST,
	NEW_REQUESTV2,
//	GET_REQUESTS,
	GET_REQUESTSV2,
	CLOSE_REQUEST;
}
