export const platformconstants = {
    // - C O N S T A N T S
    DOCK_CURRENT_CONFIGURATION: '-DOCK_CURRENT_CONFIGURATION-',
    JWTTOKEN_KEY: '-JWTTOKEN_KEY-',
    JWTTOKEN_EXPIRATION_TIME_KEY: '-JWTTOKEN_EXPIRATION_TIME_KEY-',
    CREDENTIAL_KEY: '-CREDENTIAL-KEY-',
    VALID_STATE: 'LU5FT0NPTS5JTkZJTklUWS1ERVZFTE9QTUVOVC1WQUxJRCBTVEFURSBTVFJJTkct',
    DEFAULT_ICON_PLACEHOLDER: '/assets/media/defaulticonplaceholder.png',
    DEFAULT_AVATAR_PLACEHOLDER: '/assets/media/defaulticonplaceholder.png',
    DEFAULT_CORPORATION_AVATAR_PLACEHOLDER: '/assets/media/defaultcorporationavatar.png'
}
