export const platformconstants = {
    // - C O N S T A N T S
    DOCK_CURRENT_CONFIGURATION_KEY: '-DOCK_CURRENT_CONFIGURATION-KEY-',
    PARTIAL_PART_KEY: '-PARTIAL-PART-KEY-',
    JWTTOKEN_KEY: '-JWTTOKEN_KEY-',
    JWTTOKEN_EXPIRATION_TIME_KEY: '-JWTTOKEN_EXPIRATION_TIME_KEY-',
}
