# - C I R C L E C I   C O N T I N U O U S   I N T E G R A T I O N
# Download, compile, test and deploy to the production server at Heroku.
# CircleCI has the ability to deploy to Heroku and integrate more than one
#   project on the same pipeline.
# 
# Rules:
# 1. Try to keep the front end and the back end aligned. So event they seem to be two different applications I can reduce
#    exceptions if I drop both on staging even if there are no changes on one or both of the applications. The stage
#    branch that triggers Heroku installation id "test".
# 2. There is no possibility to run docker containers. So I have to create an special configuration to start in parallel
#    the ApiSimulator on the frontend and the application for acceptance on the backend. Get back the manual start and
#    stop for the ApiSimulator and include the code on the Heroku repository only.
# 3. Test deployment go to the **stage** instances. To deploy tests we should be sure that all test checks have been passed
#    or we can deploy changes that go to stage without passing unit testing or acceptance testing. So test should do all
#    previous stages until some sort of optimization is found.
# 4. Until script adjustment acceptance is optional to allow a commit to pass stage.
#
# BRANCHES:
# The lowest level branch is the 'experimental' at this level we only require the environment to load and the code to compile.
# The next level is 'development'
# The final level is 'test'. With this branch we should compile and do full tests to the code. If tests complete then
#   we deploy the code to the Heroku server for restart on the Stage servers.
#
version: 2.1
jobs:
  start-job:
    docker:
      - image: apimastery/apisimulator
    steps:
      - run:
          name: PROJECT - Check node version
          working_directory: Printer3D-frontend
          command: |
            java -version

  compile-frontend-job:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run:
          name: FRONTEND - Install the framework
          working_directory: Printer3D-frontend
          command: |
            node -v
            npm install
      - run:
          name: FRONTEND - Compile Angular code
          working_directory: Printer3D-frontend
          command: |
            npm run build:prod
  compile-backend-job:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: BACKEND - Compile SpringBoot code
          working_directory: Printer3D-backend
          command: |
            ./gradlew clean bootJar

  test-backend-job:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          _JAVA_OPTIONS: "-Xmx3g"
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      - image: circleci/postgres:11.1
        environment:
          POSTGRES_USER: inno-user
          POSTGRES_DB: inno-password
    steps:
      - checkout
      - run:
          name: BACKEND - Start the application in local profile
          working_directory: Printer3D-backend
          environment:
            PORT: 5130
            JDBC_DATABASE_URL: "jdbc:postgresql://0.0.0.0:5432/postgres"
            DB_USER: inno-user
            DB_PASSWORD: inno-password
            SPRING_PROFILES_ACTIVE: acceptance
          command: |
            ./gradlew bootRun
          background: true
      - run:
          name: BACKEND - Waiting for application start
          environment:
            PORT: 5130
          working_directory: Printer3D-backend
          command: |
            dockerize -wait tcp://localhost:${PORT}/actuator/health -timeout 3m
      - run:
          name: BACKEND - Unit Testing application
          working_directory: Printer3D-backend
          environment:
            PORT: 5130
            JDBC_DATABASE_URL: "jdbc:postgresql://0.0.0.0:5432/postgres"
            DB_USER: inno-user
            DB_PASSWORD: inno-password
          command: |
            ./gradlew test
      - store_test_results:
          path: ~/project/Printer3D-backend/build/test-results
      - store_artifacts:  
          path: ~/project/Printer3D-backend/build/libs
  test-frontend-job:
    docker:
      - image: circleci/node:12.16.3-browsers
    environment:
      PORT: 5100
      CYPRESS_KEY: 9eebb605-a163-4da0-bb36-6af73faddf1b
    steps:
      - checkout
      - run:
          name: FRONTEND - Install the framework
          working_directory: Printer3D-frontend
          command: |
            node -v
            npm install
      - run:
          name: FRONTEND - Start backend simulator & run tests
          working_directory: Printer3D-frontend
          command: |
            npm run acceptance:simulator
            npm run build:prod
            npm run test:prod
            npm run acceptance:cypress
      - store_test_results:
          path: ~/project/Printer3D-frontend/cypress/cucumber-json

  stage-to-heroku:
    docker:
      - image: circleci/node:12.16.3-browsers
        environment:
          HEROKU_FRONTEND_APP_NAME: printer3d-frontend-stage
          HEROKU_FRONTEND_API_KEY: 0898c4c7-7389-4023-940b-ba5d7d799f73
      - image: circleci/openjdk:11-jdk
        environment:
          _JAVA_OPTIONS: "-Xmx3g"
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
          HEROKU_BACKEND_APP_NAME: printer3d-backend-stage
          HEROKU_BACKEND_API_KEY: 0898c4c7-7389-4023-940b-ba5d7d799f73
    steps:
      - checkout
      - run:
          name: BACKEND - Update application to Stage
          working_directory: Printer3D-backend
          command: |
            git config --global user.email "adamantinoo.git@gmail.com"
            git config --global user.name "Adam antinoo"
            git init
            git add .gitignore
            git add *.*
            git add src
            git add gradle
            git add gradlew
            git commit -m "-[HEROKU] Commiting code for deployment"
      - run:
          name: BACKEND - Deploy Master to Heroku
          working_directory: Printer3D-backend
          environment:
            _JAVA_OPTIONS: "-Xmx3g"
            GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
            HEROKU_BACKEND_APP_NAME: printer3d-backend-stage
            HEROKU_BACKEND_API_KEY: 0898c4c7-7389-4023-940b-ba5d7d799f73
          command: |
            git push https://heroku:$HEROKU_BACKEND_API_KEY@git.heroku.com/$HEROKU_BACKEND_APP_NAME.git master --force
      - run:
          name: FRONTEND - Generate deploy code for Stage
          working_directory: Printer3D-frontend
          command: |
            node -v
            sed -i '/bahmutov.add/d' package.json
            npm install
            # npm run build:dev
      - run:
          name: FRONTEND - Clone Heroku repository
          working_directory: Printer3D-frontend
          command: |
            git config --global user.email "adamantinoo.git@gmail.com"
            git config --global user.name "Adam antinoo"
            git init
            rm -rf .gitignore
            git add *.*
            git add config
            git add src
            # git add dist
            git commit -m "-[HEROKU] Commiting code for deployment"
      - run:
          name: Deploy Master to Heroku
          environment:
            HEROKU_FRONTEND_APP_NAME: printer3d-frontend-stage
            HEROKU_FRONTEND_API_KEY: 0898c4c7-7389-4023-940b-ba5d7d799f73
          working_directory: Printer3D-frontend
          command: |
            git push https://heroku:$HEROKU_FRONTEND_API_KEY@git.heroku.com/$HEROKU_FRONTEND_APP_NAME.git master --force
 

workflows:
  version: 2
  printer3d-deploy:
    jobs:
      - start-job:
          filters:
            branches:
              only:
                - experimental
                - development
                - test
                - hotfix
                - test-frontend
                - test-backend
                - master

      - compile-backend-job:
          requires:
            - start-job
          filters:
            branches:
              only:
                - development
                - experimental
      - compile-frontend-job:
          requires:
            - start-job
          filters:
            branches:
              only:
                - development
                - experimental

      - test-backend-job:
          requires:
            - start-job
          filters:
            branches:
              only:
                - test
                - hotfix
      - test-frontend-job:
          requires:
            - start-job
          filters:
            branches:
              only:
                - test
                - hotfix

      - stage-to-heroku:
          requires:
            - test-backend-job
            - test-frontend-job
          filters:
            branches:
              only:
                - test
                - hotfix
