# - C I R C L E C I   C O N T I N U O U S   I N T E G R A T I O N
# Download, compile, test and deploy to the production server at Heroku.
# CircleCI has the ability to deploy to Heroku and integrate more than one
#   project on the same pipeline.
# V1:
# Start creationg the workflow to clone the repository, then build the 'frontend'
#   module of the project.
version: 2.1
jobs:
  install-frontend-job:
    docker:
      - image: circleci/node:latest
    environment:
      # Customize the environment values to use on the jobs
      PORT: 5100
    steps:
      - checkout
      - run:
          name: Validate existence of the target project
          working_directory: Printer3D-frontend
          command: |
            echo "server port: ${PORT}"
            pwd
      - restore_cache:
          keys:
            - printer3d-frontend-{{ checksum "~/project/Printer3D-frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - printer3d-frontend-
      - run:
          name: Validate node version in use and install
          working_directory: Printer3D-frontend
          command: |
            echo '>> Printer3D - frontend: Start Continuous Integration'
            node -v
            npm install
      - save_cache:
          paths:
            - ~/Printer3D-frontend/node_modules
          key: printer3d-frontend-{{ checksum "~/project/Printer3D-frontend/package.json" }}
  build-frontend-job:
    docker:
      - image: circleci/node:latest
    environment:
      # Customize the environment values to use on the jobs
      PORT: 5100
    steps:
      - checkout
      - restore_cache:
          keys:
            - printer3d-frontend-{{ checksum "~/project/Printer3D-frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - printer3d-frontend-
      - run:
          name: Build the deploy version for the frontend
          working_directory: Printer3D-frontend
          command: |
            npm run build:prod
      - save_cache:
          paths:
            - ~/Printer3D-frontend/deploy
          key: printer3d-frontend-deploy
  build-backend-job:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/PostgreSQL:latest
    environment:
      # Customize the environment values to use on the jobs
      PORT: 5110
    steps:
      - checkout
      - restore_cache:
          keys:
            - printer3d-backend-{{ checksum "~/project/Printer3D-backend/dependencies.gradle" }}
            - printer3d-backend-
      - run:
          name: Validate environment version
          working_directory: Printer3D-backend
          command: |
            ./gradlew -version
      - run:
          name: Compile and Build the backend spring boot application
          working_directory: Printer3D-backend
          command: |
            ./gradlew clean build
      - save_cache:
          paths:
            - ~/Printer3D-backend/build
          key: printer3d-backend-{{ checksum "~/project/Printer3D-backend/dependencies.gradle" }}

workflows:
  version: 2
  Printer3D-Frontend-Build:
    jobs:
      - install-frontend-job:
          filters:
            branches:
              only:
                - experimental
      - build-frontend-job:
          requires:
            - install-frontend-job
          filters:
            branches:
              only:
                - development
      - build-backend-job:
          filters:
            branches:
              only:
                - development
