name: Artifact version update
description: Set the project version with Maven from the GitVersion results to generate the artifact.

inputs:
  gitUserName:
    required: true
    description: GitHub username for authorized actions.
  gitToken:
    required: true
    description: GitHub authorization token.
  commitVersion:
    required: true
    description: The apllication artifact commit version calculated for this execution.
  workingDirectory:
    required: true
    description: The working directory where to run the 

runs:
  using: 'composite'
  steps:
    # S E T   V E R S I O N
    - name: Cache local Maven respository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2
        restory-keys: ${{ runner.os }}-m2
    - name: Update local POM version
      id: update_version
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: >
        mvn versions:set
        -DnewVersion=${{ inputs.commitVersion }}
        -DprocessAllModules=true
        -DgenerateBackupPoms=false
