server:
  port: 9500
  version: 0.2.0
info:
  tags:
    environment: acceptance
    version: 0.2.0

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

spring:
  jackson:
    serialization.indent_output: true
  datasource:
    url: "jdbc:postgresql://postgres-dev:5432/postgres"
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: inno-user
    password: inno-password
  liquibase:
    liquibase-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging.logstash:
  enabled: true

