server:
  port: \${PORT}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: \${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: \${DB_USER}
    password: \${DB_PASSWORD}
  liquibase:
    liquibase-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
