server:
  port: ${PORT}

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
  info:
    id: health
    sensitive: false
    enabled: true

spring:
  jackson:
    serialization.indent_output: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    liquibase-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    originDomains: "http://localhost:5102"

logging:
  logstash:
    enabled: true
  request:
    headers: true
