server:
  port: 9500
  version: 0.2.0
info:
  tags:
    environment: test
    version: 0.2.0

endpoints:
  enabled: false

spring:
  jackson:
    serialization.indent_output: true
  jpa:
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS PRINTER3D
#    driver-class-name: org.postgresql.Driver
#    platform: postgres
    username: inno-user
    password: inno-password
  liquibase:
    liquibase-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
