@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "org.dimensinfin.printer3d.backend.production.request.persistence.RequestEntityV2"
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_40556892 { 
   	label=dimensinfin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1770082975 { 
   	label=printer3d
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Builder149946628[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Builder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   onConstruction: RequestEntityV2 [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ build(): RequestEntityV2</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RequestEntityV2556550044[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RequestEntityV2</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   amount: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   completedDate: Instant [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   contents: List&lt;RequestItem&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   customer: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   iva: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   label: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   paid: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   paymentDate: Instant [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   requestDate: Instant [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   state: RequestState [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   total: float [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ close(): RequestEntityV2</TD></TR>
<TR><TD ALIGN="LEFT" >+ setAmount(amount: float): RequestEntityV2</TD></TR>
<TR><TD ALIGN="LEFT" >+ setPaymentDate(paymentDate: Instant): RequestEntityV2</TD></TR>
<TR><TD ALIGN="LEFT" >+ signalCompleted()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RequestItem921183698[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RequestItem</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   itemId: UUID [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   missing: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quantity: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   type: RequestContentType [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setMissing(missing: int): RequestItem</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Builder149946628 -> RequestEntityV2556550044[label="onConstruction
[0..1]"];
RequestEntityV2556550044 -> RequestItem921183698[label="contents
[0..*]"];
    
}
@enduml