version: '3'
services:
  printerd-frontent-development-backend-apisimulator:
    container_name: printerd-frontent-development-backend-apisimulator
    image: apimastery/apisimulator:1.8
    ports:
      - "5110:6090"
    volumes:
      - /home/adam/Development/DimensinfinSoftware/Dimensinfin3D/Printer3D-frontend/support/printer3d-backend-simulation:/printer3d-backend-simulation
    command: "bin/apisimulator start /printer3d-backend-simulation -p 6090"
