apiVersion: v1
kind: Service
metadata:
  name: postgres-sv
  namespace: develop
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30203
  selector:
    app: postgres
