apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: printer3d-backend-stage-svc-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: printer3d-backend
  namespaceSelector:
    matchNames:
    - stage
  endpoints:
  - port: "8080"
    path: "/actuator/prometheus"
    interval: 30s
